version: '3.3'
services:
 postgres:
  image: postgres:13
  environment:
    - POSTGRES_DB=proyect
    - POSTGRES_USER=juan
    - POSTGRES_PASSWORD=1234proyect
  ports: 
    - 5432:5432
  volumes:
    - ./postgres_data:/var/lib/postgresql/data

 pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=juan@mail.com
      - PGADMIN_DEFAULT_PASSWORD=juan1234
    ports:
      - 5050:80
